---
- name: debian | Adding knot-dns Repository (Debian)
  apt_repository:
    repo: "{{ knot_dns_debian_repo }}"
    state: "present"
  when: ansible_distribution == "Debian"

- name: debian | Adding knot-dns Repository (Ubuntu)
  apt_repository:
    repo: "{{ knot_dns_ubuntu_repo }}"
    state: "present"

- name: debian | Installing knot-dns
  apt:
    name: "knot"
    state: "present"

- name: add knot config file
  template: src=knot.conf.j2 dest=/etc/knot/knot.conf

- name: add zone file
  template: src=file.zone.j2 dest=/var/lib/knot/{{ domain }}.zone
